name: Build and Deploy  

on:
  push:                 
    branches:           
      - main    

jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
      - name: Build Project
        working_directory: ./
        run: |
          yarn install
          yarn build
      - uses: actions/checkout@master
      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        env:
          FTP_SERVER: ${{ secrets.FTP_SERVER }}     
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
          REMOTE_DIR: ${{ secrets.FTP_SERVER_DIR }}
          LOCAL_DIR: dist
          ARGS: --delete --parallel=4